--1 CREATE TABLE NEWSTUDENT
CREATE TABLE NEWSTUDENT(
S_ID INT PRIMARY KEY,S_NAME VARCHAR(50),AGE INT,
COURSE VARCHAR(30),FEES NUMERIC
) 
--2 INSERTING FIVE RECORDS 
INSERT INTO NEWSTUDENT VALUES(1,'ROHAN',23,'PYTHON FULL STACK',15000.00),
(2,'RAHUL',24,'DEVOPS',40000.00),(3,'PRANAV',25,'SALESFORCE',50000.00),
(4,'KARTIK',30,'REACT',60000.00),(5,'RAMESH',28,'MERNSTACK',18000.00)

--3 DISPLAY ALL RECORDS
SELECT * FROM NEWSTUDENT

--4 DISPLAY RECORDS FEES GREATOR THAN 20000
SELECT *FROM NEWSTUDENT WHERE FEES>20000

--5 SORTING FEES USING ORDER BY CLAUSE IN DESCENDING FORM
SELECT * FROM NEWSTUDENT ORDER BY FEES DESC

--6 UPDATING RECORDS WHERE S_ID 2
UPDATE STUDENT SET COURSE = 'PYTHON' WHERE S_ID = 2

--7 DELETING ONE RECORDS WHERE S_ID=4
DELETE FROM NEWSTUDENT WHERE S_ID=4

--8 REMOVING ALL RECORDS
TRUNCATE TABLE NEWSTUDENT;

--9 DELETED TABLE PERMANENTLY
DROP TABLE NEWSTUDENT